// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.CardItem_MouseLeftButtonDown(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:AsyncCommandBase.Execute(System.Object)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.ItemOnMouseLeftButtonDown(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.ItemsCommonBtn_Checked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.ItemsCommonBtn_Unchecked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.ItemsEpicBtn_Checked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.ItemsEpicBtn_Unchecked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.ItemsFilterTB_TextChanged(System.Object,System.Windows.Controls.TextChangedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.ItemsRareBtn_Checked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.ItemsRareBtn_Unchecked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.NewItem_MouseLeftButtonDown(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.PowerOnMouseLeftButtonDown(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.RelicsCommonBtn_Checked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.RelicsCommonBtn_Unchecked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.RelicsEpicBtn_Checked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.RelicsEpicBtn_Unchecked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.RelicsFilterTB_TextChanged(System.Object,System.Windows.Controls.TextChangedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.RelicsRareBtn_Checked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.AdventureSetup.RelicsRareBtn_Unchecked(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.addNewBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.addPowersButton_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.allCardsLBL_MouseLeftButtonDown(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.allCardsSV_PreviewMouseWheel(System.Object,System.Windows.Input.MouseWheelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.backBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.cardPreview_LostFocus(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.cardPreviewGrid_PreviewMouseLeftButtonDown(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.closeAddDialogBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.deckSV_PreviewMouseWheel(System.Object,System.Windows.Input.MouseWheelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.drawnCardsBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.drawnCardsBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.endGameBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.inGameSV_PreviewMouseWheel(System.Object,System.Windows.Input.MouseWheelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.loadCardsBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.loadCardsBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.locationCardsBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.spellCardsBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.InGamePage.unitCardsBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.MainWindow.btnCloseApp_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.MainWindow.btnMiniApp_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.MainWindow.loadUI(System.Object,System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.MainWindow.toolbarGrid_MouseLeftButtonDown(System.Object,System.Windows.Input.MouseEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.MainWindow.updateUI(System.Object,System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.ProfilePage.btnRefresh_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.ProfilePage.btnRefresh_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.ProfilePage.gameTypeBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.ProfilePage.inGameBtn_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.WelcomePage.BtnPort_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:desktop.WelcomePage.portNumber_KeyDown(System.Object,System.Windows.Input.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:desktop.AdventureSetup.adventurePowers")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:desktop.AdventureSetup.allItems")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:desktop.AdventureSetup.allPowers")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:desktop.AdventureSetup.allRelics")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:desktop.data.Models.SetCard.assets")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:desktop.MainWindow.LRect.bottom")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:desktop.MainWindow.LRect.left")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:desktop.MainWindow.LRect.right")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:desktop.MainWindow.LRect.top")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:ContentUpdate")]
